[package]
name = "green/anachronousframework"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[server-dependencies]

#main:
profilestore = "lm-loleris/profilestore@1.0.2" #data store
cmdr = "evaera/cmdr@1.12.0" #command console

#optional:


[dev-dependencies]

#main:

#optional:


[dependencies]

#main:
red = "red-blox/red@2.3.0" #secure signals and events
ratelimit = "red-blox/ratelimit@1.0.1" #doesnt come with red for some reason

react-roblox = "jsdotlua/react-roblox@17.2.1" #UI library

trove = "sleitnick/trove@1.5.0"
dash = "dev-alastair/dash@1.1.2" #for tables / has intellisense
promise = "evaera/promise@4.0.0" #for some bug prevention

input = "sleitnick/input@2.3.0" #user input
shake = "sleitnick/shake@1.1.0" #camera shaking
boattween = "boatbomber/boattween@1.0.1" #more tweening options

stater = "denispionicul/stater@1.0.3" #for monster logic


#optional:

#ui-labs = "rocky28447/ui-labs@0.1.0"
#smartbone-2 = "jakeywastaken/smartbone-2@0.4.2"
#topbarplus = "aspecky/topbarplus@2.9.3" #real version doesnt work right "1foreverhd/topbarplus@3.0.2"