[package]
name = "dev-alastair/dash"
description = """
A collection of core utilities expanding the capabilities of Lua in Roblox, tweaked for intellisense support.
https://github.com/dev-alastair/dash-wally
Up-to-date: Oct 9 2024
Most recent commit: a870873
"""
version = "1.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"


[dependencies]

[dev-dependencies]
Jest = "jsdotlua/jest@3.6.1-rc.2"
JestGlobals = "jsdotlua/jest-globals@3.6.1-rc.2"